---
title: "Projects_in_DA_EDA"
author: "Niccolò Cherubini & Ivan Kostine"
date: "4/26/2022"
output:
  html_document:
    code_folding: hide
          
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Useful packages
```{r echo=TRUE, warning=FALSE,message=FALSE}
library(ggplot2)
library(DT)
library(igraph)
library(Hmisc)  
library(tidyverse)
library(tidyquant)
library(ggthemes)
library(RColorBrewer)
library(corrplot)
library(psych)
library(GGally)
library(corrr)
library(corrplot)
library(ggcorrplot)
library(kableExtra)
library(DataExplorer)
library(inspectdf)
library(dplyr)
library(explore)
library(rpart)
library(PerformanceAnalytics)
library(caret)
library(hrbrthemes)
library(ggridges)
library(ggpubr)
```

# EDA

## Data Wrangling
```{r, include=TRUE}
germancredit = read.csv("../data/GermanCredit.csv", sep = ";", header = TRUE)

str(germancredit)

#Thanks to str we can have an overview of variables types and specs: all features are integers but from what we have been said some of them are categorical, we can convert them to factors/categorical variables. Let first convert the response variable from numeric to string (More clear):

germancredit["RESPONSE"][germancredit["RESPONSE"] == 0] = "Bad Rating"
germancredit["RESPONSE"][germancredit["RESPONSE"] == 1] = "Good Rating"

#convert all concerned variables to factors
cols = c(2,4:10,12:22,24:32)
germancredit[,cols]= lapply(germancredit[,cols], as.factor)
cols_num = c(3,11,23)
germancredit[,cols_num]= lapply(germancredit[,cols_num], as.numeric)


#Remove col"OBS."
germancredit = germancredit[,-1]

summary(germancredit)

#With the help of the summary function we are able to identify some incorrect values such as education = -1, age = 125 and guarantor = 2 (only one occurrence of 2, might be a typo) 

#Change the incorrect values, to be noted in the final report !!!

germancredit[37,8]=1
germancredit[234,18]=1
germancredit[537,22]=75




str(germancredit)

datatable(germancredit)
write.csv2(germancredit, file = "../data/germancredit_final.csv", sep = ",")

```


```{r include=FALSE}
n = dim(germancredit)[1]
p = dim(germancredit)[2]
quant = 31
```


## Data Explorer

```{r}

#we check for missing values and final data type distribution
introduce(germancredit)
paste("This data set contains",sum(rowSums(is.na(germancredit)))/nrow(germancredit),"missing values")

paste("Data Set is",(sum(complete.cases(germancredit))/nrow(germancredit))*100,"% complete")

#plot_missing(germancredit)


#data type distribution
plot_intro(germancredit)
```

## Categorical variables analysis:

```{r}

#Categorical variables analysis:



germancredit %>% group_by(RESPONSE) %>% summarise(freq = n())

ggplot(germancredit, aes(x = RESPONSE)) + geom_bar(aes(fill = factor(RESPONSE))) + labs(color = "",
    fill = "", x = "response", y = "count", title = "Rating distribution", subtitle = "0: Bad Rating - 1: Good Rating",
    caption = "Rating distribution") + theme_bw()

#
#
#Correlation matrix for categorical variables.

unused_cols = c(2,10,22,31)
model.matrix(~0+., data=germancredit[,-unused_cols]) %>% 
  cor(use="pairwise.complete.obs") %>% 
  ggcorrplot(show.diag = FALSE, type="upper", lab = FALSE, lab_size=2, ggtheme = ggplot2::theme_gray, colors = c("#C41E3A", "white", "#228B22" ), tl.cex = 6, insig = "blank", method = "square")
```


# Numerical variables analysis:

```{r}

#Numerical / continuous variables analysis:

plot_histogram(germancredit, title = "Histograms of GermanCredit variables", ggtheme = theme_bw())

plot_density(germancredit, title ="Density plots of GermanCredit variables", ggtheme = theme_bw())

plot_boxplot(germancredit, title = "Credit Rating within numerical variables", by = 'RESPONSE', ncol = 2)


mydata <- germancredit[, c(2,10,22)]
chart.Correlation(mydata, histogram=TRUE, pch=19)


```


```{r}

#some plots to visually see how variables interact together:

#explore(germancredit)
germancredit %>% explore(AGE, target = RESPONSE) #Before the age of env.32, most of client have a bad credit rating but after 32, people start to be "good".

germancredit %>% explore(AGE, target = AMOUNT) #No big difference in amount credits boxplot

germancredit %>% explore(RESPONSE, target = AGE) #No large difference in median age between good and bad credit rating

#What explains the switch of trend after 32 years old ?

germancredit %>% explore(JOB, target = AGE) #No large difference in median age between good and bad credit rating

germancredit %>% explore(AGE, target = EDUCATION) #No large difference in median age between good and bad credit rating

#
#
germancredit %>% explore(EDUCATION, target = RESPONSE)

germancredit %>% explore(RESPONSE, target = JOB)



germancredit %>% explore(DURATION, target = AMOUNT)

germancredit %>% explore(AGE, target = DURATION)



germancredit %>% explore(SAV_ACCT, target = AGE)

germancredit %>% explore(SAV_ACCT, target = AMOUNT)

germancredit %>% explore(CHK_ACCT, target = AMOUNT)

germancredit %>% explore(CHK_ACCT, target = AGE)

```




# Bad and Good rated personas


```{r}
visual_set <-  germancredit

visual_set$CHK_ACCT = as.numeric(visual_set$CHK_ACCT)
visual_set$SAV_ACCT = as.numeric(visual_set$SAV_ACCT)

visual_set["CHK_ACCT"][visual_set["CHK_ACCT"] == 1] = "< 0 DM"
visual_set["CHK_ACCT"][visual_set["CHK_ACCT"] == 2] = "0 < x < 200 DM"
visual_set["CHK_ACCT"][visual_set["CHK_ACCT"] == 3] = "≥ 200 DM"
visual_set["CHK_ACCT"][visual_set["CHK_ACCT"] == 4] = "no checking account"
visual_set["SAV_ACCT"][visual_set["SAV_ACCT"] == 1] = "< 100 DM"
visual_set["SAV_ACCT"][visual_set["SAV_ACCT"] == 2] = "100 ≤ x < 500 DM"
visual_set["SAV_ACCT"][visual_set["SAV_ACCT"] == 3] = "500 ≤ x < 1000 DM"
visual_set["SAV_ACCT"][visual_set["SAV_ACCT"] == 4] = "> 1000 DM"
visual_set["SAV_ACCT"][visual_set["SAV_ACCT"] == 5] = "unknown/no savings account"


visual_set$CHK_ACCT = as.factor(visual_set$CHK_ACCT)
visual_set$SAV_ACCT = as.factor(visual_set$SAV_ACCT)
```


```{r Bad rated client}




```

```{r Good rated client}

#checking account graph

check_acct_plot <- visual_set %>%
  ggplot( aes(x=CHK_ACCT, fill=RESPONSE)) +
    geom_histogram(alpha=0.6, position="fill", stat = "count" ) +
    scale_fill_manual(values=c("tomato1", "steelblue3")) +
    theme_ipsum(axis_title_size = 14, axis_text_size = 12) +
    labs(fill="Applicant credit rating", title = "Applicant checking account repartition") + 
    scale_x_discrete(name="", limits=c("< 0 DM","0 < x < 200 DM", "≥ 200 DM", "no checking account")) +
    scale_y_continuous(name="Credit rating repartition", labels = scales::percent_format(accuracy = 1))
    
check_acct_plot

#age graph

age_set = dplyr::select(visual_set, RESPONSE, AGE)


age_plot = ggplot(data = age_set, aes(x = AGE, fill = RESPONSE)) + 
  geom_density(data = subset(age_set, RESPONSE == "Good Rating"), binwidth = 5, color="white", position = "identity", mapping = aes(y = ..density..),alpha=0.6) +
  geom_density(data = subset(age_set, RESPONSE == "Bad Rating"), binwidth = 5, color="white", position = "identity", 
                 mapping = aes(y = - ..density.. ), alpha = 0.6) +
  scale_x_continuous("Age", breaks = c(seq(0, 75, by=5))) +
  scale_y_continuous("Rating Density", labels = NULL) +
  scale_fill_manual(values=c("tomato1", "steelblue3")) +
  coord_flip() +
  theme(panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_blank(),
  # Change axis line
  axis.line.y = element_line(colour = "black"),
  axis.line.x = element_blank(),
  axis.ticks.x = element_blank(),
  ) + ggtitle("Rating and applicant age")

age_plot


#amount graph

amount_plot = ggplot(data = visual_set, aes(x = AMOUNT, fill = RESPONSE)) +
  geom_density(data = subset(visual_set, RESPONSE == "Good Rating"), binwidth = 5, color="white", position = "identity", mapping = aes(y = ..density..),alpha=0.6) +
  geom_density(data = subset(visual_set, RESPONSE == "Bad Rating"), binwidth = 5, color="white", position = "identity",
                 mapping = aes(y = - ..density.. ), alpha = 0.6) +
  scale_x_continuous("Credit Amount", breaks = c(seq(0, 20000, by=1000))) +
  scale_y_continuous("Rating Density", labels = NULL) +
  scale_fill_manual(values=c("tomato1", "steelblue3")) +
  coord_flip() +
  theme(panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_blank(),
  # Change axis line
  axis.line.y = element_line(colour = "black"),
  axis.line.x = element_blank(),
  axis.ticks.x = element_blank(),
  ) + ggtitle("Rating and applicant age")

amount_plot




#duration - amount

duration_amount = germancredit %>% explore(DURATION, target = AMOUNT)

duration_amount

#savings account - amount

savings_amount = ggplot(visual_set, aes(x=SAV_ACCT, y=AMOUNT, fill=SAV_ACCT)) + 
    geom_boxplot(alpha=0.3) +
    theme(legend.position="none") +
    scale_fill_brewer(palette="BuPu") +
    scale_x_discrete(name="Savings Account", limits=c("< 100 DM","100 ≤ x < 500 DM", "500 ≤ x < 1000 DM","> 1000 DM", "unknown/no savings account")) +
    scale_y_continuous(name="Requested Amount") +
    labs(title = "Savings Account and Requested Amount")
    

savings_amount



#history


#employment


#present_resident

#install_rate

#job


```





