```{r import_libraries}

#Support Vector Machines
library(e1071)
library(tidyverse)
library(dplyr)
library(knitr)
library(kableExtra)
library(caret)
library(pROC)

```

```{r import_dataset}

#We do some basic wrangling specific to SVM model with Caret
data = read.csv("../data/germancredit_final.csv", sep = ";", header = TRUE)

data["RESPONSE"][data["RESPONSE"] == "Bad Rating"] = "Bad.Rating"
data["RESPONSE"][data["RESPONSE"] == "Good Rating"] = "Good.Rating"

data$RESPONSE <- as.factor(data$RESPONSE)

str(data)
```

```{r split_dataset}

#We split the data into train (80%) and test (20%)
set.seed(1234)
trainIndex <- createDataPartition(data$RESPONSE, p = .8,
                                  list = FALSE)
train.df <- data[ trainIndex,]
test.df <- data[-trainIndex,]

```

```{r svm_linear_caret}
set.seed(123)

train_control <- trainControl(method = "repeatedcv", number = 10, repeats = 3, sampling="down", classProbs = TRUE)
svml_fit <- train(RESPONSE ~ ., train.df, 
                              method = "svmLinear",
                              trControl = train_control, 
                              tuneGrid = expand.grid(C = seq(0.1, 2, length = 20)))
svml_fit
svml_predict <- predict(svml_fit, test.df)

```
```{r confusion_matrix_svm_linear}
confusion_matrix_svml <- confusionMatrix(svml_predict, as.factor(test.df$RESPONSE), positive= "Good.Rating")
confusion_matrix_svml
```

```{r roc_svm_linear}
svml_predict_prob <- predict(svml_fit, test.df, type="prob")
roc_curve_svml <- roc(test.df$RESPONSE, svml_predict_prob[,2], plot = TRUE, print.auc = TRUE)
plot(roc_curve_svml,print.auc = TRUE ,asp = NA, col="red")
title(main="ROC curve using Support Vector Machines with Linear Kernel")
```

```{r svm_radial}

set.seed(123)
train_control_radial <- trainControl(method = "repeatedcv", number = 3, repeats = 3, sampling="down", classProbs = TRUE)
C<-c(0.1, 1, 10)
sigma<-seq(0.1, 10, length = 20)

grid_radial <-expand.grid(C=C, sigma=sigma)
svmr_fit <- train(RESPONSE ~., data = train.df, 
                  method = "svmRadial", 
                  trControl = train_control_radial, 
                  preProcess = c("center","scale"),
                  tuneGrid = grid_radial,
                  tuneLength = 10)

svmr_fit

svmr_predict <- predict(svmr_fit, test.df)
svmr_predict

```
```{r confusion_matrix_svmr}
confusion_matrix_svmr <- confusionMatrix(svmr_predict, as.factor(test.df$RESPONSE), positive="Good.Rating")
confusion_matrix_svmr

```
```{r roc_curve_svmr}
svmr_predict_prob <- predict(svmr_fit, test.df, type="prob")
roc_curve_svmr <- roc(test.df$RESPONSE, svmr_predict_prob[,2], plot = TRUE, print.auc = TRUE)
plot(roc_curve_svmr,print.auc = TRUE ,asp = NA)
title(main="ROC curve using Support Vector Machines with Radial Kernel")
```

```{r double_plot_roc}
roc_curve_svml <- roc(test.df$RESPONSE, svml_predict_prob[,2], plot = TRUE, print.auc = TRUE, asp=NA, add=TRUE)


```
